// Auto-generated by scripts/split-i18n.js
import Common from './common.json';
import Connection from './connection.json';
import Settings from './settings.json';
import Config from './config.json';
import RAG from './rag.json';
import PDF from './pdf.json';
import RAGPanel from './ragPanel.json';
import Upload from './upload.json';
import UploadZone from './uploadZone.json';
import KB from './kb.json';
import Zotero from './zotero.json';
import EnvVars from './envVars.json';
import ConfigButtons from './configButtons.json';
import MCP from './mcp.json';
import Sessions from './sessions.json';
import Sidebar from './sidebar.json';

export default {
  Common: Common,
  Connection: Connection,
  Settings: Settings,
  Config: Config,
  RAG: RAG,
  PDF: PDF,
  RAGPanel: RAGPanel,
  Upload: Upload,
  UploadZone: UploadZone,
  KB: KB,
  Zotero: Zotero,
  EnvVars: EnvVars,
  ConfigButtons: ConfigButtons,
  MCP: MCP,
  Sessions: Sessions,
  Sidebar: Sidebar,
} as const;
